### PR TITLE
Changes for LSE-163

### PR DESCRIPTION
**Pull request by timj**
* US Letter not A4
* Remove \req for now (was Gaia req macro)
* Add some additional commands from LSE-163
* Use standard maketitle/author/title commands

### CODE REVIEW

**Comment by womullan** [comment]
I use \req in a statement of work I am writing with KT …

it is handy for properly labled things ..

**Comment by timj** [comment]
Ok. I used a different `\req` in LSE-163 so I'll change the LSE-163 end of things to use a different macro for requirements annotations.

**Comment by timj** [comment]
I've reverted the `\req` change.

**Comment by womullan** [comment]
i have less dependencies I could switch to yours ..

**Comment by timj** [comment]
no. I've made the fix already. Wasn't much. My requirement anchors added margin notes so I made that explicit in the name.

**Comment by womullan** [comment]
these are more example documents ..  I did try to make them all LSST shaped. I would leave the images in this folder but indeed another repo of share images fo the actual dm-docs would be good.

**Pull request merged**
