### PR TITLE
Correct institutional name for IPAC

### PR DESCRIPTION
**Pull request by gpdf**
The formal name we use is "Caltech/IPAC".

### CODE REVIEW

**Review by timj — APPROVED** [review]
This is fine for your purposes. Will that form be okay for ApJ papers?

**Comment by gpdf** [comment]
@timj 
> [...] Will that form be okay for ApJ papers?

Do you have a recent example of a paper with affiliations generated from that file?  I don't have a clear mental picture of what it looks like.

**Comment by timj** [comment]
The ApJ overview paper for example: https://iopscience.iop.org/article/10.3847/1538-4357/ab042c

It takes that affiliation text and puts it directly in the paper without any attempt to reformat or extract semantics. That was the reason the file was created in the first place.

**Review by womullan — APPROVED** [review]

**Comment by gpdf** [comment]
It may look a bit awkward, but if a paper comes out before @jonathansick gets to the refactoring, it'll be OK.

**Pull request merged**
