### PR TITLE
 2019 year in cookiecutter and some fixed to the body.tex

### PR DESCRIPTION
**Pull request by womullan**
just minor stuff

### CODE REVIEW

**Comment by jdswinbank** [comment]
Yes... but not all. I think we should only be carrying acronyms which are very generic or which are LSST-specific. Let's not store things like BBC, TSESO or MREN — they're just likely to cause collisions.

**Comment by womullan** [comment]
we have a lsst specific gloassry for the other stuff -- i reduced the myacronyms a lot though now and moved some to the gloassary.txt  or lsstacronyms.txt in etc

**Comment by jdswinbank** [comment]
Right — LSST specific abbrevs should go in `lsstacronyms.txt` and really generic stuff in `glossary.txt`. But having ”BBC” recorded *anywhere* by default just means that somebody will refer to the British Broadcasting Corporation and we'll end up with a glossary entry claiming it's a German shipping company and confusion will reign.

I reckon we should only add such easily-confused abbreviations to specific documents on a case-by-case basis.

**Comment by womullan** [comment]
pretty much what i did - BBC is still there .. but it could be removed altogether if that is what you mean

**Comment by jonathansick** [comment]
Right, what I'm getting at is that if an acronym isn't fit for lsst-texmf because it's not universal enough, it's probably for universal enough for the template either (I.e.,`macronyms.tex` should start empty).

**Comment by jdswinbank** [comment]
I would remove BBC and anything else that isn't either LSST-specific or completely unambiguous in basically all circumstances from this repository (including both the `etc` directory and `myacronyms.txt` — which I think is what we're talking about, as `myacronyms.tex` will be autogenerated and shouldn't be versioned at all).

**Comment by womullan** [comment]
the myacronyms here is from the template and is copied when you use cookie cutter to make a new doc. I will remove more and leave one example in there ..

**Pull request merged**
