### PR TITLE
add workflow_dispatch to dockercache triggers

### PR DESCRIPTION
**Pull request by jhoblitt**
'cause some people are impatient...

### CODE REVIEW

**Comment by jhoblitt** [comment]
There we go... docker hub is now showing the last push to master from `ci.yaml`.  This may not be completely necessary but still seems like a nice-to-have.

**Comment by timj** [comment]
I have no idea what "workflow_dispatch" does so not entirely sure I can review.

**Comment by womullan** [comment]
I had ont appreciated that docker was caching the base image - so this forces it to refhresh whereas normal CI would just use the exisiting base ?  I guess that is good ...  otherwise how was this ever getting updated -- Jonathan ocasionally did it ?

**Review by womullan — APPROVED** [review]
this should also be documented (in dveloper.lsst.io?).. so we know what it is later

**Comment by timj** [comment]
I think @jonathansick set all this up so he probably should comment.

**Review by jonathansick — DISMISSED** [review]
I'm in principle ok with adding a `workflow_dispatch` to refresh the base image on-demand. However, your PR isn't much to go on — what is making you need to refresh the base image? I forsaw a weekly schedule as being sufficient and don't really see why we'd need folks to have a more active enagement. Could you explain @jhoblitt ?

**Comment by womullan** [comment]
> I'm in principle ok with adding a `workflow_dispatch` to refresh the base image on-demand. However, your PR isn't much to go on — what is making you need to refresh the base image? I forsaw a weekly schedule as being sufficient and don't really see why we'd need folks to have a more active enagement. Could you explain @jhoblitt ?

I believe @jhoblitt was faced with a problem in the base image causing an issue in the CI and update was needed to fix it. For some repos heavily dependent on the image for testing the ability to force an update may be occasionally useful. So I would move to rebase and merge this.

**Comment by jonathansick** [comment]
I'm closing as I don't think this is needed and there hasn't been any additional discussion since the initial issues were raised.

**Comment by jonathansick** [comment]
@womullan ok, if you think it'll help that's ok then.

**Comment by jhoblitt** [comment]
I was away yesterday.  I concur with @wil that have the ability to manually trigger a run is desirable, even if it isn't strictly necessary.

**Pull request merged**
