### PR TITLE
First attempt at python acronyms extraction

### PR DESCRIPTION
**Pull request by timj**
Not ready to merge yet but basic functionality exists.

### CODE REVIEW

**Comment by womullan** [comment]
Just trying it .. lots of difficult to understand errors about files  and then it complains "RuntimeError: Duplicate definitions of CAM differ" It produces no new file .. I think it a=ought to produce the acronyms anyway better than nothing ..   even when I delete CAM from myacronyms.txt it still gives this error ..

**Comment by womullan** [comment]
SO it seem to still look in myacronyms.tex as well as myacronyms.txt .. hence my problem above. Now it runs through . The Gaia version warns when I have multiple definitions this does not .. so I have in acronyms.tex  .. 
BW & BandWidth \\\hline
BW & Baade's Window (special, high-density area on the sky) \\\hline

this may be ok but the user should be warned to pick one to put in the myacronyms.txt .. I think also in Gaia we only put the FIRST one ..  so we have not so many duplicates (again warning the user about that).

**Comment by timj** [comment]
Yes. I'll fix those. It's not ready for release yet but it does all the basics. The CAM problem is that there are two definitions in the LSST file in lsst-texmf/bin -- I could treat them like the Gaia ones and only complain if there is no clarification in the local file.

**Comment by jdswinbank** [comment]
Do we really want something home-grown for this? Seems like the [glossaries](https://ctan.org/pkg/glossaries?lang=en) package would be adequate...

**Comment by timj** [comment]
I did think of glossaries but @womullan explained why it didn't work for them in Gaia. I think part of the problem is that you have to declare explicitly that you are using a glossary term when you write the latex whereas the gaia approach is to scan the text trying to find acronyms. I do remember trying to upgrade LPM-17 to use glossaries instead of `glossary` and I gave up because it wasn't able to do what SRD wanted. I'm willing to be convinced.

**Comment by jdswinbank** [comment]
I don't really want to convince people one way or the other — I used glossaries in DMTN-020, and they worked fine, and I'm cautious that rolling our own involves implementation effort up front (which it looks like you've already broken the back of) and ongoing maintenance/documentation/compatibility/etc issues, which are not free. If @womullan reckons this is a good trade off, I'm not actually going to argue (for a change).

**Comment by womullan** [comment]
Tim has pretty much done the Gaia thing (still needs tweaking) - it did not require much maintenance on Gaia later.  Yes the problem with glossary is you have to  remember to \gls{} entries  and people are lazy or will simply forget - so then you need a script to check up on that. The acronym approach basically does most of the job for you on any document at anytime and warns about the bits you need to take care of - it also requires no modification of the actual tex..

**Comment by timj** [comment]
I think these two commits were on the wrong branch and I can remove them.

**Comment by womullan** [comment]
well we could apply them to master .. actually your script could go to well if not already done ..

**Comment by timj** [comment]
I think @jdswinbank added the references separately in #117

**Pull request merged**
